%% Import data from spreadsheet
% Script for importing data from the following spreadsheet:
%
%    Workbook: /Users/Katherine/Documents/Excel
%    Files/1422Trimmed_region_report.xls Worksheet:
%    1422Trimmed_region_report.txt
%
% To extend the code for use with different selected data or a different
% spreadsheet, generate a function instead of a script.

% Auto-generated by MATLAB on 2015/05/04 08:47:22

%% Import the data
function Trimmedregionreport = importGeneral(dirname,filename)   %filename will have .xls extension
filenameWithTxt = strtok(filename, 'xls');
filenameWithTxt = [filenameWithTxt 'txt'];
[~, ~, Trimmedregionreport] = xlsread(cell2mat([dirname '/' filename]),cell2mat(filenameWithTxt));
Trimmedregionreport = Trimmedregionreport(:,[1,7]);
Trimmedregionreport(cellfun(@(x) ~isempty(x) && isnumeric(x) && isnan(x),Trimmedregionreport)) = {''};

