%% Import data from spreadsheet
% Script for importing data from the following spreadsheet:
%
%    Workbook: /Users/Katherine/Dropbox/Nicol Project Compare Run of 8
%    Samples to Run of 16 Samples/Sample 04 6194 run 16 samples.xlsx
%    Worksheet: Sample 04 6194Trimmed_region_re
%
% To extend the code for use with different selected data or a different
% spreadsheet, generate a function instead of a script.

% Auto-generated by MATLAB on 2015/05/28 10:16:37

%% Import the data
function Trimmedregionreport = importxlsxSpecific(dirname,filename)
class(filename)
[~, ~, Trimmedregionreport] = xlsread([dirname '/' filename]);
Trimmedregionreport = Trimmedregionreport(:,:);
Trimmedregionreport(cellfun(@(x) ~isempty(x) && isnumeric(x) && isnan(x),Trimmedregionreport)) = {''};

